import Head from "next/head";
import Link from "next/link";

import {MdAccountCircle} from 'react-icons/md';

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
      <Link href={'/Login'} > <MdAccountCircle/> </Link>
      </body>
    </>
  );
}
