import Head from "next/head";
import {MdAccountCircle} from 'react-icons/md';
import LoginUi from "./Login";

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <LoginUi/>
      </body>
    </>
  );
  }

