import Head from "next/head";
<<<<<<< HEAD
import Link from "next/link";

import {MdAccountCircle} from 'react-icons/md';

export default function Home() {
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
      <Link href={'/Login'} > <MdAccountCircle/> </Link>
      </body>
    </>
  );
=======
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return <></>;
>>>>>>> d1197f7a24904fdf0872238059a20eee5ddbcba0
}
